export const BROWSER_FIELD_LABELS: Record<string, string> = {
  browser: "Browser",
  "browser.enabled": "Browser Enabled",
  "browser.allowSystemProfileImport": "Allow System Profile Import",
  "browser.cdpUrl": "Browser CDP URL",
  "browser.executablePath": "Browser Executable Path",
  "browser.headless": "Browser Headless Mode",
  "browser.noSandbox": "Browser No-Sandbox Mode",
  "browser.attachOnly": "Browser Attach-only Mode",
  "browser.defaultProfile": "Browser Default Profile",
  "browser.profiles": "Browser Profiles",
  "browser.profiles.*.engine": "Browser Profile Engine",
  "browser.profiles.*.cdpPort": "Browser Profile CDP Port",
  "browser.profiles.*.cdpUrl": "Browser Profile CDP URL",
  "browser.profiles.*.userDataDir": "Browser Profile User Data Dir",
  "browser.profiles.*.mcpCommand": "Browser Profile Chrome MCP Command",
  "browser.profiles.*.mcpArgs": "Browser Profile Chrome MCP Args",
  "browser.profiles.*.driver": "Browser Profile Driver",
  "browser.profiles.*.executablePath": "Browser Profile Executable Path",
  "browser.profiles.*.headless": "Browser Profile Headless Mode",
  "browser.profiles.*.attachOnly": "Browser Profile Attach-only Mode",
  "browser.extensionRelay": "Browser Extension Relay",
  "browser.extensionRelay.allowLegacyAuth": "Allow Legacy Browser Relay Auth",
  "browser.evaluateEnabled": "Browser Evaluate Enabled",
  "browser.snapshotDefaults": "Browser Snapshot Defaults",
  "browser.snapshotDefaults.mode": "Browser Snapshot Mode",
  "browser.tabCleanup": "Browser Tab Cleanup",
  "browser.tabCleanup.enabled": "Browser Tab Cleanup Enabled",
  "browser.cdpPolicy": "Browser CDP Policy",
  "browser.cdpPolicy.dangerouslyAllowPrivateNetwork":
    "Browser CDP Dangerously Allow Private Network",
  "browser.cdpPolicy.allowedHostnames": "Browser CDP Allowed Hostnames",
  "browser.cdpPolicy.blockedHostnames": "Browser CDP Blocked Hostnames",
  "browser.cdpPolicy.allowRfc2544BenchmarkRange": "Browser CDP Allow RFC 2544 Benchmark Range",
  "browser.cdpPolicy.allowIpv6UniqueLocalRange": "Browser CDP Allow IPv6 Unique Local Range",
};
